// Code generated by goctl. DO NOT EDIT.
package types

type BaseModel struct {
	Id   int64  `json:"id"`            // id
	Name string `json:"name,optional"` // 名称
	Data string `json:"data,optional"` // 数据
}

type BaseIdList struct {
	IdList []int64 `json:"idList"` // id集合
}

type BaseDataList struct {
	DataList []string `json:"dateList"` // Data集合
}

type BaseId struct {
	Id int64 `form:"id"` // id
}

type PathReq struct {
	Id   int64  `path:"id"`   // id
	Name string `path:"name"` // 名称
}

type UserListReq struct {
	Account   string `json:"account,optional"`             // 账号
	Username  string `json:"username,optional"`            // 用户名
	Gender    int64  `json:"gender,options=1,2,3"`         // 性别 1：未设置；2：男性；3：女性
	Email     string `json:"email,optional"`               // 邮箱
	Phone     string `json:"phone,optional"`               // 手机号
	Current   int64  `json:"current,optional,default=1"`   // 当前页码
	PageSize  int64  `json:"pageSize,optional,default=20"` // 每页数量
	CreatedBy int64  `json:"createdBy,optional"`           // 创建者id
	CreatedAt string `json:"createdAt,optional"`           // 创建时间
	UpdatedBy int64  `json:"updatedBy,optional"`           // 更新者id
	UpdatedAt string `json:"updatedAt,optional"`           // 更新时间
	DeletedBy int64  `json:"deletedBy,optional"`           // 删除者id
	DeletedAt string `json:"deletedAt,optional"`           // 删除时间
}

type UserModel struct {
	Id        int64  `json:"id,optional"`          // id
	Account   string `json:"account,optional"`     // 账号
	Username  string `json:"username,optional"`    // 用户名
	Gender    int64  `json:"gender,options=1,2,3"` // 性别 1：未设置；2：男性；3：女性
	CreatedBy int64  `json:"createdBy,optional"`   // 创建者id
	CreatedAt string `json:"createdAt,optional"`   // 创建时间
	UpdatedBy int64  `json:"updatedBy,optional"`   // 更新者id
	UpdatedAt string `json:"updatedAt,optional"`   // 更新时间
	DeletedBy int64  `json:"deletedBy,optional"`   // 删除者id
	DeletedAt string `json:"deletedAt,optional"`   // 删除时间
}

type UserSimpleModel struct {
	Id       int64  `form:"id,optional"`       // id
	Account  string `form:"account,optional"`  // 账号
	Username string `form:"username,optional"` // 用户名
	Email    string `form:"email,optional"`    // 邮箱
	Phone    string `form:"phone,optional"`    // 手机号
}

type UserLoginPasswordModel struct {
	Account  string `json:"account"`  // 账号
	Password string `json:"password"` // 密码
}

type UserPageResp struct {
	List     []*UserModel `json:"list"`     // 列表数据
	Current  int64        `json:"current"`  // 当前页码
	PageSize int64        `json:"pageSize"` // 每页数量
	Total    int64        `json:"total"`    // 列表总数
}

type UserLoginResp struct {
	Id           int64  `json:"id"`           // 用户id
	Account      string `json:"account"`      // 账号
	Username     string `json:"username"`     // 登录账号
	Gender       int64  `json:"gender"`       // 性别 1：未设置；2：男性；3：女性
	Avatar       string `json:"avatar"`       // 头像
	AccessToken  string `json:"token"`        // token
	AccessExpire int64  `json:"accessExpire"` // 过期时间戳
	RefreshAfter int64  `json:"refreshAfter"` //
}

type FileUploadReq struct {
	Id       int64   `form:"id"`                // 父级-id
	Type     int64   `form:"type,optional"`     // 类型 1：类型1；2：类型2
	FileList []*byte `form:"fileList,optional"` // 文件列表
}

type FileShowReq struct {
	Id      int64  `form:"id"`               // 文件-id
	FileUrl string `form:"fileUrl,optional"` // 文件地址
}
