// Code generated by goctl. DO NOT EDIT.

package usermodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	zeroUsersFieldNames          = builder.RawFieldNames(&ZeroUsers{})
	zeroUsersRows                = strings.Join(zeroUsersFieldNames, ",")
	zeroUsersRowsExpectAutoSet   = strings.Join(stringx.Remove(zeroUsersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	zeroUsersRowsWithPlaceHolder = strings.Join(stringx.Remove(zeroUsersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	zeroUsersModel interface {
		Insert(ctx context.Context, data *ZeroUsers) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ZeroUsers, error)
		Update(ctx context.Context, data *ZeroUsers) error
		Delete(ctx context.Context, id int64) error
	}

	defaultZeroUsersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ZeroUsers struct {
		Id          int64     `db:"id"`           // id
		Account     string    `db:"account"`      // 账号
		Username    string    `db:"username"`     // 用户名
		Password    string    `db:"password"`     // 密码
		Gender      int64     `db:"gender"`       // 性别 1：未设置；2：男性；3：女性
		UpdatedBy   int64     `db:"updated_by"`   // 更新人
		UpdatedAt   time.Time `db:"updated_at"`   // 更新时间
		CreatedBy   int64     `db:"created_by"`   // 创建人
		CreatedAt   time.Time `db:"created_at"`   // 创建时间
		DeletedAt   time.Time `db:"deleted_at"`   // 删除时间
		DeletedFlag int64     `db:"deleted_flag"` // 是否删除 1：正常  2：已删除
	}
)

func newZeroUsersModel(conn sqlx.SqlConn) *defaultZeroUsersModel {
	return &defaultZeroUsersModel{
		conn:  conn,
		table: "`zero_users`",
	}
}

func (m *defaultZeroUsersModel) withSession(session sqlx.Session) *defaultZeroUsersModel {
	return &defaultZeroUsersModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`zero_users`",
	}
}

func (m *defaultZeroUsersModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultZeroUsersModel) FindOne(ctx context.Context, id int64) (*ZeroUsers, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", zeroUsersRows, m.table)
	var resp ZeroUsers
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultZeroUsersModel) Insert(ctx context.Context, data *ZeroUsers) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, zeroUsersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Account, data.Username, data.Password, data.Gender, data.UpdatedBy, data.CreatedBy, data.DeletedAt, data.DeletedFlag)
	return ret, err
}

func (m *defaultZeroUsersModel) Update(ctx context.Context, data *ZeroUsers) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, zeroUsersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Account, data.Username, data.Password, data.Gender, data.UpdatedBy, data.CreatedBy, data.DeletedAt, data.DeletedFlag, data.Id)
	return err
}

func (m *defaultZeroUsersModel) tableName() string {
	return m.table
}
