// Code generated by goctl. DO NOT EDIT.
// Source: ucenter.proto

package filestorage

import (
	"context"

	"go-zero-micro/rpc/code/ucenter/ucenter"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseDataList  = ucenter.BaseDataList
	BaseIdList    = ucenter.BaseIdList
	BaseModel     = ucenter.BaseModel
	BaseModelList = ucenter.BaseModelList
	BaseResp      = ucenter.BaseResp
	FileInfo      = ucenter.FileInfo
	FileList      = ucenter.FileList
	User          = ucenter.User
	UserLoginResp = ucenter.UserLoginResp

	FileStorage interface {
		// 文件上传
		FileUpload(ctx context.Context, in *FileList, opts ...grpc.CallOption) (*BaseResp, error)
		// 文件下载
		FileDownload(ctx context.Context, in *FileInfo, opts ...grpc.CallOption) (ucenter.FileStorage_FileDownloadClient, error)
	}

	defaultFileStorage struct {
		cli zrpc.Client
	}
)

func NewFileStorage(cli zrpc.Client) FileStorage {
	return &defaultFileStorage{
		cli: cli,
	}
}

// 文件上传
func (m *defaultFileStorage) FileUpload(ctx context.Context, in *FileList, opts ...grpc.CallOption) (*BaseResp, error) {
	client := ucenter.NewFileStorageClient(m.cli.Conn())
	return client.FileUpload(ctx, in, opts...)
}

// 文件下载
func (m *defaultFileStorage) FileDownload(ctx context.Context, in *FileInfo, opts ...grpc.CallOption) (ucenter.FileStorage_FileDownloadClient, error) {
	client := ucenter.NewFileStorageClient(m.cli.Conn())
	return client.FileDownload(ctx, in, opts...)
}
